import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.wiseadmit.io/")
    page.get_by_role("button", name="Are you a student?").click()
    expect(page.get_by_role("button", name="Login")).to_be_visible()
    expect(page.get_by_role("link", name="Wise Admit")).to_be_visible()
    page.get_by_role("button", name="Login").click()
    page.get_by_role("menuitem", name="Login as a Student").click()
    page.get_by_text("Create Account", exact=True).click()
    page.get_by_role("textbox", name="First Name").click()
    page.get_by_role("textbox", name="First Name").fill("Nishan")
    page.get_by_role("textbox", name="Last Name").click()
    page.get_by_role("textbox", name="Last Name").press("CapsLock")
    page.get_by_role("textbox", name="Last Name").fill("K")
    page.get_by_role("textbox", name="Last Name").press("CapsLock")
    page.get_by_role("textbox", name="Last Name").fill("Kafle")
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("t.kafle191645@gmail.com")
    page.get_by_role("button").nth(1).click()
    page.get_by_role("searchbox", name="search").click()
    page.get_by_role("searchbox", name="search").fill("nepal")
    page.get_by_role("searchbox", name="search").press("Enter")
    page.get_by_placeholder("1 (702) 123-").click()
    page.get_by_placeholder("1 (702) 123-").fill("+977 981 799 5154")
    page.get_by_role("textbox", name="Create a password").click()
    page.get_by_role("textbox", name="Create a password").fill("2000@Nishan")
    page.locator("div").filter(has_text="Welcome back, future grads!").nth(2).click()
    page.get_by_role("textbox", name="Re-enter password").click()
    page.get_by_role("textbox", name="Re-enter password").fill("2000@nishan")
    page.get_by_role("button", name="Create an account").click()
    page.get_by_role("button").nth(3).click()
    page.get_by_role("textbox", name="Re-enter password").click()
    page.get_by_role("textbox", name="Re-enter password").fill("2000@Nishan")
    page.get_by_role("button", name="Create an account").click()
    page.get_by_role("button", name="Log in").click()
    page.locator("input[name=\"password\"]").click()
    page.locator("input[name=\"password\"]").fill("2000@nishan")
    page.get_by_role("button", name="Log in").click()
    page.locator("input[name=\"password\"]").click()
    page.locator("form").get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.locator("input[name=\"password\"]").click()
    page.locator("input[name=\"password\"]").press("ArrowLeft")
    page.locator("input[name=\"password\"]").press("ArrowLeft")
    page.locator("input[name=\"password\"]").press("ArrowLeft")
    page.locator("input[name=\"password\"]").press("ArrowLeft")
    page.locator("input[name=\"password\"]").press("ArrowLeft")
    page.locator("input[name=\"password\"]").fill("2000@Nishan")
    page.get_by_role("button", name="Log in").click()
    expect(page.get_by_role("link", name="Dashboard")).to_be_visible()
    expect(page.get_by_text("Welcome to WiseAdmit!")).to_be_visible()
    expect(page.get_by_role("link", name="Check your Wisescore")).to_be_visible()
    expect(page.get_by_text("Nishan Kafle")).to_be_visible()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
